services:
  db-user:
    image: postgres:15
    container_name: db-user
    restart: always
    env_file:
      - ./backend/user-service/.env
    ports:
      - "5432:5432"
    volumes:
      - db-user-data:/var/lib/postgresql/data
    networks:
      - tamle-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      db-user:
        condition: service_healthy
    env_file:
      - ./backend/user-service/.env
    ports:
      - "8081:8081"
    networks:
      - tamle-net
  api-gateway:
    build:
      context: ./backend/api-gateway-service
      dockerfile: Dockerfile
    container_name: api-gateway-service
    depends_on:
      - user-service
    env_file:
      - ./backend/api-gateway-service/.env
    ports:
      - "8080:8080"
    networks:
      - tamle-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - api-gateway
    ports:
      - "5173:80"
    networks:
      - tamle-net
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules


networks:
  tamle-net:
    driver: bridge

volumes:
  db-user-data:
